### ISSUE TITLE
Write down the first version of Region

### ISSUE THREAD

**Issue by tisonkun** [tisonkun/tikv-dev-guide#12]
Reference

* https://tikv.org/deep-dive/scalability/data-sharding/

**Comment by pingyu** [comment]
I'd like to write this chapter. Please assign to me, thanks~ @tisonkun

**Comment by tisonkun** [comment]
@pingyu thanks for taking over this. Go ahead!

**Comment by tisonkun** [comment]
@pingyu Hi, do you have an estimate of this task?

**Comment by pingyu** [comment]
> @pingyu Hi, do you have an estimate of this task?

I think I can submit a PR in the coming Mid Autumn holiday.

**Comment by tisonkun** [comment]
@pingyu thanks!

**Comment by pingyu** [comment]
> > @pingyu Hi, do you have an estimate of this task?
> 
> I think I can submit a PR in the coming Mid Autumn holiday.

PTAL, thanks~ @tisonkun 
PR: #47 
https://github.com/pingyu/tikv-dev-guide/blob/scalability-region/src/understanding-tikv/scalability/region.md
