### ISSUE TITLE
Write down the first version of Coprocessor chapter

### ISSUE THREAD

**Issue by tisonkun** [tisonkun/tikv-dev-guide#2]
https://github.com/tisonkun/tikv-dev-guide/blob/main/src/understanding-tikv/coprocessor/intro.md

**Comment by skyzh** [comment]
I’ll take this, maybe this month.

**Comment by tisonkun** [comment]
@skyzh cheers! Thanks for your help.

**Comment by Xuanwo** [comment]
> I’ll take this, maybe this month.

Any plan to updates on this? Maybe I can write some part of it too.

**Comment by skyzh** [comment]
Not any yet. Shall we first elaborate some ideas on this 🤪🤪

**Comment by skyzh** [comment]
Some quick ideas:

Contrary from things like "TiKV source code reading", I would focus on how a request is served and transformed from TiDB to local KV storage this time. Developers should know how data are like when a request reaches a certain stage. e.g. How is DAG represented, how does evaluation framework represents a vector, how storage layer stores key value pairs.

* Overall Architecture of TiKV Coprocessor: DAG, Analyze, Checksum handler. We would focus on the first part (DAG).
* What is a TiDB request like? (kvproto / tipb introduction)
* How does Coprocessor handle cross-region requests? (Intro to storage snapshot, region, pd, and how TiDB aggregates results from TiKV)
* What happens inside Coprocessor?
  * DAG
  * Executor
  * Aggregator
  * Expression Evaluation Framework
  * In-memory representation (chunk format)
* How does copr get key-value from storage, and how are keys / values parsed?
* Raw Coprocessor, copr2.0 or Coprocessor Plugin

Does this outline look good to you? cc @andylokandy @Xuanwo

**Comment by xxchan** [comment]
> how a request is served and transformed from TiDB to local KV storage

> What is a TiDB request like? (kvproto / tipb introduction)

As a newbee, I also think this will be very helpful! BTW, maybe we can also add a similar chapter (or link) in tidb-dev-guide?

**Comment by xxchan** [comment]
> What is a TiDB request like? (kvproto / tipb introduction)

This may be related? @skyzh  https://github.com/pingcap/tidb-dev-guide/pull/72/files#diff-6757fa0daa0222e227ad8ba44971b32f53b7f8e9ff5a9ccff8a3964caa920c37R169-R175

**Comment by skyzh** [comment]
@xxchan Looks good!

**Comment by xxchan** [comment]
Hi @skyzh, I have a question, which seems to be contained in your outline: 
Why the executors in the DAG request are an array? How to represent a DAG in an array? (There's no explanation about the representation.) 🤔 

From the source code, I guess it's just unary executors from bottom to top...

**Comment by skyzh** [comment]
I guess it is stored as RPN. I’ll cover this part in the dev guide.

**Comment by xxchan** [comment]
Do you have a schedule? I'm eager to read it 😍😍😍

**Comment by skyzh** [comment]
> Do you have a schedule? I'm eager to read it 😍😍😍

2-3 weeks :)

**Comment by tisonkun** [comment]
@skyzh I think it is two weeks later 🐶

**Comment by skyzh** [comment]
I've been busy last two weeks, so I'll begin this this week!
